import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from '@clerk/themes';
import Header from "./_components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MedInsight",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme: "dark", // Use dark mode
     
      elements: {
        card: "border border-[#02c9e3] shadow-md ", // Neon blue border with subtle shadow
        formFieldInput: "text-[#050d15] placeholder-gray-400", // White text for inputs
        formFieldLabel: "text-[#050d15]", // Light gray labels
        formButtonPrimary:
          "bg-[#02c9e3] text-white hover:bg-[#00a1c5] transition duration-300", // Neon blue button with hover effect
        footer: "text-gray-400", // Dimmed text for footer
      },
    }}
     >

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
